codecov:
  ci:
    - "!ci.appveyor.com"

coverage:
  precision: 2
  round: down
  range: "50...100"

  ignore:
    - "tests/*"


  notify:
    slack:
      default:
        url:
          secret:4FCetOj2urXyoT02ONiv62804o/mPp++K5/L3QlnSVdeovhfAQWVlROA+ZKPGdi0atAN+8lfoZIfk8qPY5JgGQOkcPMCoxVL+OaAgLWJlBdB7j5YfHERyf0LH6neP8E0qAqzk8xYFv3wqGSmcxwx1DRS5qx3LwZNuIoyF2Nhsg4=
        threshold: null
        branches: null
        attachments: "sunburst, diff"

comment: off
